# Site settings
title: Open EV Data
description: Open Dataset of Electric Vehicles and their specs
baseurl: "/open-ev-data"  # the subpath of your site, e.g. /blog

# GitHub metadata
github:
  owner_name: KilowattApp
  owner_url: https://github.com/KilowattApp
  repository_url: https://github.com/KilowattApp/open-ev-data


