name: Ruby Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Adjust this to match your Ruby version
        bundler-cache: true # This will cache your gem dependencies
        working-directory: scripts

    - name: Install dependencies
      run: |
        cd scripts
        bundle install

    - name: Run tests
      run: ruby scripts/test/validators/ev_data_test.rb